version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    rust: "1.86"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
    create_environment:
      - poetry lock
      - poetry install --with dev,docs
      - poetry run maturin develop
    install:
      - export PATH="$PATH:$HOME/.asdf/installs/rust/1.86.0/bin" && cargo install sphinx-rustdocgen && poetry run sphinx-build -b html docs $READTHEDOCS_OUTPUT/html
