version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    rust: "1.86"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - cargo install sphinx-rustdocgen
      - export PATH="$PATH:$HOME/.cargo/bin"
    create_environment:
      - poetry lock
      - poetry install --with dev,docs
    install:
      - poetry run sphinx-build -b html docs docs/_build/html
