from pathlib import Path
from typing import List, Tuple

from numpy import ndarray

def read_selected_layers(file_list: List[Path]) -> ndarray: ...
def read_layer(file: str) -> ndarray: ...
def read_file(filepath: Path) -> Tuple[ndarray, float, int]: ...
def get_z(filepath: Path) -> float: ...
def correct_x(x: float) -> None: ...
def correct_y(y: float) -> None: ...
