name: Auto Version Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package version
        id: info
        uses: rabbitson87/get-cargo-package-info@v1
        with:
          package: |
            version

      - name: Check if Tag Exists
        id: check_tag
        run: |
          VERSION=${{ fromJson(steps.info.outputs.object).package.version }}
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create and Push Git Tag
        if: env.TAG_EXISTS == 'false'
        run: |
          VERSION=${{ fromJson(steps.info.outputs.object).package.version }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$VERSION"
          git push origin "$VERSION"
